onerror {resume}
quietly WaveActivateNextPane {} 0
add wave -noupdate /mp3_tb/clk
add wave -noupdate /mp3_tb/read_a
add wave -noupdate /mp3_tb/write_a
add wave -noupdate /mp3_tb/wmask_a
add wave -noupdate /mp3_tb/address_a
add wave -noupdate /mp3_tb/wdata_a
add wave -noupdate /mp3_tb/resp_a
add wave -noupdate /mp3_tb/rdata_a
add wave -noupdate /mp3_tb/dut/mcpu/cpu_datapath/if_data/clk
add wave -noupdate /mp3_tb/dut/mcpu/cpu_datapath/if_data/resp_a
add wave -noupdate /mp3_tb/dut/mcpu/cpu_datapath/if_data/rdata_a
add wave -noupdate /mp3_tb/dut/mcpu/cpu_datapath/if_data/read_a
add wave -noupdate /mp3_tb/dut/mcpu/cpu_datapath/if_data/address_a
add wave -noupdate /mp3_tb/dut/mcpu/cpu_datapath/if_data/stall
add wave -noupdate /mp3_tb/dut/mcpu/cpu_datapath/if_data/pcmux_sel
add wave -noupdate /mp3_tb/dut/mcpu/cpu_datapath/if_data/pc_out
add wave -noupdate /mp3_tb/dut/mcpu/cpu_datapath/if_data/instruction
add wave -noupdate /mp3_tb/dut/mcpu/cpu_datapath/if_data/src1
add wave -noupdate /mp3_tb/dut/mcpu/cpu_datapath/if_data/src2
add wave -noupdate /mp3_tb/dut/mcpu/cpu_datapath/if_data/dest
add wave -noupdate /mp3_tb/dut/mcpu/cpu_datapath/if_data/pc_plus2_out
add wave -noupdate /mp3_tb/dut/mcpu/cpu_datapath/if_data/pcmux_out
add wave -noupdate /mp3_tb/dut/mcpu/cpu_datapath/mem/clk
add wave -noupdate /mp3_tb/dut/mcpu/cpu_datapath/mem/ctrl
add wave -noupdate /mp3_tb/dut/mcpu/cpu_datapath/mem/alu_out
add wave -noupdate /mp3_tb/dut/mcpu/cpu_datapath/mem/pc_out
add wave -noupdate /mp3_tb/dut/mcpu/cpu_datapath/mem/br_add_out
add wave -noupdate /mp3_tb/dut/mcpu/cpu_datapath/mem/sr1_out
add wave -noupdate /mp3_tb/dut/mcpu/cpu_datapath/mem/instruction
add wave -noupdate /mp3_tb/dut/mcpu/cpu_datapath/mem/dest
add wave -noupdate /mp3_tb/dut/mcpu/cpu_datapath/mem/resp_b
add wave -noupdate /mp3_tb/dut/mcpu/cpu_datapath/mem/rdata_b
add wave -noupdate /mp3_tb/dut/mcpu/cpu_datapath/mem/read_b
add wave -noupdate /mp3_tb/dut/mcpu/cpu_datapath/mem/write_b
add wave -noupdate /mp3_tb/dut/mcpu/cpu_datapath/mem/wmask_b
add wave -noupdate /mp3_tb/dut/mcpu/cpu_datapath/mem/address_b
add wave -noupdate /mp3_tb/dut/mcpu/cpu_datapath/mem/wdata_b
add wave -noupdate /mp3_tb/dut/mcpu/cpu_datapath/mem/regfilemux_out
add wave -noupdate /mp3_tb/dut/mcpu/cpu_datapath/mem/br_en
add wave -noupdate /mp3_tb/dut/mcpu/cpu_datapath/mem/trap_zext_out
add wave -noupdate /mp3_tb/dut/mcpu/cpu_datapath/mem/marmux_out
add wave -noupdate /mp3_tb/dut/mcpu/cpu_datapath/mem/mdrmux_out
add wave -noupdate /mp3_tb/dut/mcpu/cpu_datapath/mem/ldbmux_out
add wave -noupdate /mp3_tb/dut/mcpu/cpu_datapath/mem/zext_8_out
add wave -noupdate /mp3_tb/dut/mcpu/cpu_datapath/mem/shift_out
add wave -noupdate /mp3_tb/dut/mcpu/cpu_datapath/mem/ldb_zext_out
add wave -noupdate /mp3_tb/dut/mcpu/cpu_datapath/mem/gencc_out
add wave -noupdate /mp3_tb/dut/mcpu/cpu_datapath/mem/cc_out
add wave -noupdate /mp3_tb/dut/mcpu/cpu_datapath/mem/shift_a
add wave -noupdate /mp3_tb/dut/mcpu/cpu_datapath/mem/shift_d
add wave -noupdate -expand /mp3_tb/dut/mcpu/cpu_datapath/id/rfile/data
add wave -noupdate /mp3_tb/dut/mcpu/cpu_datapath/mem_wb_buf/clk
add wave -noupdate /mp3_tb/dut/mcpu/cpu_datapath/mem_wb_buf/load
add wave -noupdate /mp3_tb/dut/mcpu/cpu_datapath/mem_wb_buf/src1_in
add wave -noupdate /mp3_tb/dut/mcpu/cpu_datapath/mem_wb_buf/src2_in
add wave -noupdate /mp3_tb/dut/mcpu/cpu_datapath/mem_wb_buf/dest_in
add wave -noupdate /mp3_tb/dut/mcpu/cpu_datapath/mem_wb_buf/br_in
add wave -noupdate /mp3_tb/dut/mcpu/cpu_datapath/mem_wb_buf/instruction_in
add wave -noupdate /mp3_tb/dut/mcpu/cpu_datapath/mem_wb_buf/alu_in
add wave -noupdate /mp3_tb/dut/mcpu/cpu_datapath/mem_wb_buf/pc_in
add wave -noupdate /mp3_tb/dut/mcpu/cpu_datapath/mem_wb_buf/pc_br_in
add wave -noupdate /mp3_tb/dut/mcpu/cpu_datapath/mem_wb_buf/mar_in
add wave -noupdate /mp3_tb/dut/mcpu/cpu_datapath/mem_wb_buf/mdr_in
add wave -noupdate /mp3_tb/dut/mcpu/cpu_datapath/mem_wb_buf/src1_data_in
add wave -noupdate /mp3_tb/dut/mcpu/cpu_datapath/mem_wb_buf/src2_data_in
add wave -noupdate /mp3_tb/dut/mcpu/cpu_datapath/mem_wb_buf/dest_data_in
add wave -noupdate /mp3_tb/dut/mcpu/cpu_datapath/mem_wb_buf/ctrl_in
add wave -noupdate /mp3_tb/dut/mcpu/cpu_datapath/mem_wb_buf/ctrl_out
add wave -noupdate /mp3_tb/dut/mcpu/cpu_datapath/mem_wb_buf/src1_out
add wave -noupdate /mp3_tb/dut/mcpu/cpu_datapath/mem_wb_buf/src2_out
add wave -noupdate /mp3_tb/dut/mcpu/cpu_datapath/mem_wb_buf/dest_out
add wave -noupdate /mp3_tb/dut/mcpu/cpu_datapath/mem_wb_buf/instruction_out
add wave -noupdate /mp3_tb/dut/mcpu/cpu_datapath/mem_wb_buf/alu_out
add wave -noupdate /mp3_tb/dut/mcpu/cpu_datapath/mem_wb_buf/pc_out
add wave -noupdate /mp3_tb/dut/mcpu/cpu_datapath/mem_wb_buf/pc_br_out
add wave -noupdate /mp3_tb/dut/mcpu/cpu_datapath/mem_wb_buf/mar_out
add wave -noupdate /mp3_tb/dut/mcpu/cpu_datapath/mem_wb_buf/mdr_out
add wave -noupdate /mp3_tb/dut/mcpu/cpu_datapath/mem_wb_buf/src1_data_out
add wave -noupdate /mp3_tb/dut/mcpu/cpu_datapath/mem_wb_buf/src2_data_out
add wave -noupdate /mp3_tb/dut/mcpu/cpu_datapath/mem_wb_buf/dest_data_out
add wave -noupdate /mp3_tb/dut/mcpu/cpu_datapath/mem_wb_buf/br_out
add wave -noupdate -expand /mp3_tb/memory/mem
TreeUpdate [SetDefaultTree]
WaveRestoreCursors {{Cursor 1} {0 ps} 0} {{Cursor 2} {2203337 ps} 0}
quietly wave cursor active 1
configure wave -namecolwidth 481
configure wave -valuecolwidth 260
configure wave -justifyvalue left
configure wave -signalnamewidth 0
configure wave -snapdistance 10
configure wave -datasetprefix 0
configure wave -rowmargin 4
configure wave -childrowmargin 2
configure wave -gridoffset 0
configure wave -gridperiod 1
configure wave -griddelta 40
configure wave -timeline 0
configure wave -timelineunits ns
update
WaveRestoreZoom {0 ps} {59389 ps}
